apiVersion: apps/v1
kind: Deployment
metadata:
  name: toshi-darkweb-graph-builder-deployment
  labels:
    app: toshi-bitcoin-parser
    tier: darkweb-graph
spec:
  replicas:
  selector:
    matchLabels:
      app: toshi-darkweb-graph-builder
      tier: darkweb-graph
  template:
    metadata:
      labels:
        app: toshi-darkweb-graph-builder
        tier: darkweb-graph
    spec:
      containers:
        - name: darkweb-graph-builder
          image: "{{ .Values.darkweb.image.name }}:{{ .Values.darkweb.image.tag }}"
          imagePullPolicy: {{ .Values.darkweb.image.pullPolicy }}
          env:
            - name: RABBITMQ_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.darkweb.rabbitmq.token }}
                  key: token
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.darkweb.rabbitmq.password }}
                  key: password
